server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
spring:
  profiles:
    active: local
  datasource:
    dynamic:
      primary: jdbc-zero #设置默认的数据源
      datasource:
        jdbc-zero:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://110.40.195.147:3306/db_zero?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: librarian
          password: iMd8dj7W2A2X2f6k

